name: omnitrade_client
description: Dart client for OmniTrade API V2
version: 0.0.1
authors:
  - Helio S. Junior <helio.junior@codeminer42.com>
homepage: https://omnitrade.io/

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  chopper: ^1.1.0
  crypto: ^2.0.6

dev_dependencies:
  test: ^1.2.0
  build_runner: ^1.0.0
  chopper_generator: ^1.1.0
